{{- if .Values.githubWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "core-enterprise-sandbox.fullname" . }}-github-worker
  labels:
    {{- include "core-enterprise-sandbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: github-worker
spec:
  {{- if not .Values.githubWorker.autoscaling.enabled }}
  replicas: {{ .Values.githubWorker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "core-enterprise-sandbox.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: github-worker
  template:
    metadata:
      {{- with .Values.githubWorker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "core-enterprise-sandbox.labels" . | nindent 8 }}
        app.kubernetes.io/component: github-worker
        {{- with .Values.githubWorker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "core-enterprise-sandbox.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.githubWorker.podSecurityContext | nindent 8 }}
      containers:
        - name: github-worker
          securityContext:
            {{- toYaml .Values.githubWorker.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ .Values.githubWorker.command }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.githubWorker.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 