{{- if and .Values.githubWorker.enabled .Values.githubWorker.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "core-enterprise-sandbox.fullname" . }}-github-worker
  labels:
    {{- include "core-enterprise-sandbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: github-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "core-enterprise-sandbox.fullname" . }}-github-worker
  minReplicas: {{ .Values.githubWorker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.githubWorker.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.githubWorker.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.githubWorker.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.githubWorker.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.githubWorker.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }} 