name: Preview Deployment - Web App
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_ENTERPRISE }}
  TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  TURBO_TEAM: ${{ secrets.VERCEL_ORG_ID }}
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - clients/apps/web/**
      - clients/packages/**

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: 'clients/pnpm-lock.yaml'

      - name: Install dependencies
        working-directory: clients
        run: pnpm install

      - name: 🧪 Run unit tests
        working-directory: clients
        run: pnpm test

      - name: 📤 Pull Vercel Environment Information
        working-directory: clients
        run: pnpm dlx vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: 🏗 Build Project Artifacts
        working-directory: clients
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
        run: pnpm dlx vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: 🚀 Deploy to Vercel
        working-directory: clients
        run: pnpm dlx vercel deploy --prebuilt --archive=tgz --token=${{ secrets.VERCEL_TOKEN }}
